services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: nest-hot-reload-app
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./server:/usr/src/app
      - ./shared:/usr/src/shared
      - server_node_modules:/usr/src/app/node_modules
    env_file:
      - path: .env.production
        required: true # не обязательный, ошибки не будет если он отсутсвует, ...
        # ... но если он есть он переопределит одномённые переменные с .env.example либо добавит новые.
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB_NAME}
      WATCHPACK_POLLING: "true"
    command: npm run start:dev
  postgres:
    image: postgres:18-alpine
    container_name: postgres-db
    restart: always
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    volumes:
      - ./server/pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  server_node_modules:
